name: pum_project
description: "Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  image_picker: ^1.2.1
  share_plus: ^10.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/